<?php $block = $this->getBlock() ?>
<?php $welcomeMessage = $block->getWelcome(); ?>
<div class="container">	
			<div class="middle-header-container">	
				<div class="row">
					<div class="col-md-12">
						<?php echo $block->getChildHtml('logo') ?>	
					</div>
				</div>
			</div>
			<div class="nav-header-container">
				<div class="row">
					<div class="col-md-12">		
						<div class="nav-header-content">
						<?php echo $block->getChildHtml('megamenu') ?>
						
						<?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Search::form.mini.phtml")->toHtml();?>
						<?php echo $block->getChildHtml('minicart') ?>				
						<div class="account-dropdown" id="top-links">
							<a href="#" class="action toggle top-links-trigger" id="top-links-trigger">
								<i class="fa fa-user"></i>
							</a>
							<div class="dropdown top-links-dropdown" style="display:none;" data-mage-init='{"dropdownDialog":{
											 "appendTo":"#top-links",
											 "triggerTarget":"#top-links-trigger",
											 "closeOnMouseLeave":false,
											 "triggerClass":"active",
											 "parentClass":"active",
											 "buttons":null,
											 "defaultDialogClass":"dropdown-menu"}}'>  
								<?php echo $block->getChildHtml('top.links') ?>
							</div>
						</div>  
						<?php echo $block->getChildHtml('store_language') ?>
						<?php echo $block->getChildHtml('currency') ?>
						<button class="btn nav-toggle btn-responsive-nav">
							<em class="ion-navicon"></em>
						</button>
						</div>
					</div>
				</div>				
			</div>		
</div>



