<?php if ($block->getConfig('general_settings/enabled')): ?>
    <?php if ($block->getConfig('product_page_settings/show_related_products_by_brand')): ?>
        <?php if ($brand = $block->getBrand()): ?>
            <?php
            $_productCollection = $block->getProductCollection();
            $_helper = $this->helper('Magento\Catalog\Helper\Output');
            $themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
            $themeSettings = $themeHelper->getThemeSettings();
            $image = 'category_page_grid';
            ?>
            <?php if (count($_productCollection)): ?>
                <div class="brand-related-products">
                    <div class="block-title title">
                        <h3 id="block-heading" role="heading" aria-level="2"><?php echo $block->getConfig('product_page_settings/title_related_products'); ?></h3>
                    </div>
                    <div class="block-content content" aria-labelledby="block-heading">
                        <div class="products wrapper grid products-grid <?php echo $themeSettings['catalog']['layout_product'] ?>">
                            <ol class="products list items product-items products-related-brand">
                                <?php $iterator = 1; ?>
                                <?php foreach ($_productCollection as $_product): ?>
                                    <li class="item product product-item">
                                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                                        <div class="product-item-info" data-container="product-grid">
                                            <?php
                                            $_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
                                            $size = $themeHelper->getImageSize($this->getRatio());
                                            $productImage = $_imagehelper->init($_product, $image)->resize($size['width'], $size['height'])->getUrl();
                                            ?>
                                            <?php // Product Image  ?>
                                            <div class="product-top">
                                                <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                                    <img src="<?php echo $productImage; ?>" alt="<?php echo $_productNameStripped ?>" class="img-responsive product-image-photo"/>

                                                </a>
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && !$themeSettings['catalog']['wishlist_button']): ?>
                                                    <a href="#"
                                                       class="action towishlist"
                                                       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                       data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
                                                       data-action="add-to-wishlist"
                                                       role="button">
                                                        <i class="ion-android-favorite-outline"></i>
                                                    </a>
                                                <?php endif; ?>
                                                <div class="product-item-inner">
                                                    <div class="product actions product-item-actions">                                                                                                                           
                                                        <?php /* Append Quick View */ ?>
                                                        <?php $quickViewHelper = $this->helper('MGS\QuickView\Helper\Data'); ?>
                                                        <?php echo $quickViewHelper->aroundQuickViewHtml($_product); ?>

                                                        <?php if ($_product->isSaleable()): ?>
                                                            <?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)): ?>
                                                                <button class="action tocart primary btn btn-addto" data-mage-init='{"redirectUrl": {"url": "<?php echo $block->getAddToCartUrl($_product) ?>"}}' type="button" title="<?php echo __('Add to Cart') ?>">
                                                                    <span class="ion-ios-cart"></span>
                                                                </button>
                                                            <?php else: ?>
                                                                <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                                $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getEntityId()])
                                                                ?>
                                                                <button class="action tocart primary btn btn-addto"
                                                                        data-post='<?php echo $postData; ?>'
                                                                        type="button" title="<?php echo __('Add to Cart') ?>">
                                                                     <span class="ion-ios-cart icon"></span>
                                                                </button>
                                                            <?php endif; ?>
                                                        <?php else: ?>
                                                            <?php if ($_product->getIsSalable()): ?>
                                                                <div class="stock available"><span><?php echo __('In stock') ?></span></div>
                                                            <?php else: ?>
                                                                <div class="stock unavailable"><span><?php echo __('Out of stock') ?></span></div>
                                                            <?php endif; ?>
                                                        <?php endif; ?>

                                                        <?php if (!$themeSettings['catalog']['compare_button']): ?>

                                                            <?php
                                                            $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
                                                            ?>
                                                            <?php if (!$themeSettings['catalog']['compare_button']): ?>
                                                                <a href="#"
                                                                   class="action tocompare btn btn-addto"
                                                                   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                                   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                                   data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
                                                                   role="button">
                                                                    <i class="ion-ios-shuffle-strong"></i>
                                                                </a>
                                                            <?php endif ?>

                                                        <?php endif ?>


                                                    </div>
                                                </div>
                                                <?php if ($themeSettings['catalog']['layout_product'] == 'productv1'): ?>
                                                    <?php echo $themeHelper->getProductLabel($_product) ?>
                                                <?php endif; ?>
                                            </div>

                                            <div class="product details product-item-details">

                                                <div class="product name product-item-name">
                                                    <a class="product-item-link"
                                                       href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                                        <h4><?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></h4>
                                                    </a>
                                                </div>
                                                <?php //echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                                                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                                                <?php //echo $block->getProductDetailsHtml($_product);  ?>
                                                <?php echo $this->getLayout()->createBlock('Magento\Swatches\Block\Product\Renderer\Listing\Configurable')->setProduct($_product)->setTemplate('Magento_Swatches::product/listing/renderer.phtml')->toHtml() ?>


                                            </div>
                                        </div>
                                    </li>
                                <?php endforeach ?>
                            </ol>
                        </div>
                        <script type="text/javascript">
                    require([
                        'jquery',
                        'mgs/owlcarousel'
                    ], function ($) {
                        var brandrelatedproduct = $('.products-related-brand').owlCarousel({
                            items: 4,
                            autoplay: false,
                            autoplayHoverPause: false,
                            nav: true,
                            navText: ['<span class="ion-arrow-left-c"></span>', '<span class="ion-arrow-right-c"></span>'],
                            dots: false,
                            margin: 30,
                            responsive: {
                                0: {
                                    items: 1,
                                    margin: 0
                                },
                                480: {
                                    items: 2,
                                    margin: 20
                                },
                                768: {
                                    items: 3
                                },
                                1200: {
                                    items: 4
                                }
                            }
                        });
                    });
                </script>
                    </div>
                </div>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
