<?php $helper = $this->helper('MGS\Brand\Helper\Data'); ?>
<?php if ($block->getConfig('general_settings/enabled')): ?>
    <?php if ($block->getConfig('sidebar_settings/enabled')): ?>
        <?php
        $collection = $block->getCollection();
        if ($this->getConfig('sidebar_settings/small_image_width') != '') {
            $width = $this->getConfig('sidebar_settings/small_image_width');
        } else {
            $width = 30;
        }
        if ($this->getConfig('sidebar_settings/small_image_height') != '') {
            $height = $this->getConfig('sidebar_settings/small_image_height');
        } else {
            $height = 24;
        }
        ?>
        <?php if ($collection->count()): ?>
            <div class="block block-brand">
                <div class="block-title">
                    <h3 id="block-brand-heading"><?php echo __('Brands') ?></h3>
                </div>
                <div class="block-content">
                    <ul class="brand-list">
                        <?php foreach ($collection as $brand): ?>
                            <li class="item">
                                <div class="brand-link">
								<a title="<?php echo $brand->getName(); ?>" href="<?php echo $brand->getUrl(); ?>">
                                    <div class="col-md-4 col-sm-6 col-xs-4 brand-image">
										<div class="row">
                                         <img style="height: <?php echo $height; ?>px" class="brand-small-image img-responsive"
                                         alt="<?php echo $brand->getName(); ?>"
                                         src="<?php echo $brand->getSmallImageUrl(); ?>"/>
										</div>
									</div>
                                    <?php if ($this->getConfig('sidebar_settings/show_brand_name')): ?>
									<div class="col-md-8 col-sm-12 col-xs-8 brand-title">
									    <div class="row">
                                            <span class="title h5"><?php echo $brand->getName(); ?></span>
                                            <?php if ($this->getConfig('sidebar_settings/show_product_count')): ?>
                                                <span class="count"><?php echo __('%1', $block->getProductCount($brand)); ?></span>
                                            <?php endif; ?>
										</div>
									</div>
                                    <?php endif; ?>
                                
								</a>
								</div>
                            </li>
                        <?php endforeach; ?>
                    </ul>
                    <div class="view-all">
                        <a class="btn btn-sm btn-primary" title="<?php echo __('View All'); ?>" href="<?php echo $helper->getBrandUrl(); ?>"><?php echo __('View All'); ?></a>
                    </div>
                </div>
            </div>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
