<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magento\Theme\Block\Html\Breadcrumbs $block */
/** @var \Magento\Catalog\ViewModel\Product\Breadcrumbs $viewModel */
$viewModel = $block->getData('viewModel');
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_product = $objectManager->get('Magento\Framework\Registry')->registry('current_product');
?>
<?php $bg_breadcrumb = $block->getChildHtml('organie_breadcrumb_background');?>
<?php if($bg_breadcrumb): ?>
    <?php preg_match_all('/<img.+src=[\'"]([^\'"]+)[\'"].*>/i', $bg_breadcrumb, $matches); ?>
<?php endif ?>
<div class="breadcrumbs" 
<?php if($bg_breadcrumb && $matches[1][0]): ?>style="background-image: url('<?php echo $matches[1][0]; ?>')" <?php endif ?>>
    <h1><?php echo $_product->getName(); ?></h1>
    <div class="h5" data-mage-init='<?= /* @escapeNotVerified */ $viewModel->getJsonConfiguration() ?>'></div>
</div>
