<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php
$themeHelper = $this->helper('MGS\Mpanel\Helper\Data');
$themeSettings = $themeHelper->getThemeSettings();
?>
<?php if ($_product->isSaleable()): ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()): ?>
                <div class="field qty">            
                    <div class="control">
                        <span class="edit-qty minus" onclick="minusQty('qty')"><i class="ion-ios-minus-outline"></i></span>
                        <input type="number"
                               name="qty"
                               id="qty"
                               maxlength="12"
                               value="<?php /* @escapeNotVerified */ echo $block->getProductDefaultQty() * 1 ?>"
                               title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                               data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                               />
                        <span class="edit-qty plus" onclick="plusQty('qty')"><i class="ion-ios-plus-outline"></i></span>
                    </div>
                    <?php if ($block->displayProductStockStatus()): ?>
                        <?php if ($_product->isAvailable()): ?>
                            <div class="stock available" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
                                <span><i class="ion-ios-checkmark"></i><?php /* @escapeNotVerified */ echo __('In stock') ?></span>
                            </div>
                        <?php endif; ?>
                    <?php endif; ?>
                </div>
            <?php endif; ?>

            <div class="actions">
                <button type="submit"
                        title="<?php /* @escapeNotVerified */ echo $buttonTitle ?>"
                        class="action primary tocart btn btn-primary"
                        id="product-addtocart-button">
                    <span class="text"><?php /* @escapeNotVerified */ echo $buttonTitle ?></span>
                </button>
                <?php echo $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        function plusQty(qtyInput){
                require([
                'jquery'
                ], function(jQuery){
                        (function($) {
                                if($('#'+qtyInput).attr('disabled')!='disabled'){
                                        qty = $('#'+qtyInput).attr('value');
                                        qty = parseInt(qty);
                                        qty++;
                                        $('#'+qtyInput).val(qty);
                                }
                        })(jQuery);
                });

        }
        function minusQty(qtyInput){
                require([
                'jquery'
                ], function(jQuery){
                        (function($) {
                                if($('#'+qtyInput).attr('disabled')!='disabled'){
                                        qty = $('#'+qtyInput).attr('value');
                                        qty = parseInt(qty);

                                        if(qty>1){
                                                qty--;
                                                $('#'+qtyInput).val(qty);
                                        }
                                }
                        })(jQuery);
                });
        }
        </script>
<?php endif; ?>
<?php if ($themeSettings['product_details']['wishlist'] || $themeSettings['product_details']['compare'] || $block->canEmailToFriend()): ?>
    <div class="product-addto">       
        <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && $themeSettings['product_details']['wishlist'] != NULL): ?>
            <a href="#"
               class="action towishlist btn btn-addto"
               title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
               aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
               data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
               data-action="add-to-wishlist"
               role="button">
                <i class="ion-android-favorite-outline"></i>
            </a>
        <?php endif; ?>
        <?php
        $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
        ?>
        <?php if ($themeSettings['product_details']['compare'] != NULL && $compareHelper != NULL): ?>
            <a href="#"
               class="action tocompare btn btn-addto"
               title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
               aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
               data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>'
               role="button">
                <i class="ion-ios-shuffle-strong"></i>
            </a>
        <?php endif ?>
        <?php if ($block->canEmailToFriend()): ?>
            <a href="<?php /* @escapeNotVerified */ echo $this->helper('Magento\Catalog\Helper\Product')->getEmailToFriendUrl($_product) ?>"
               class="action mailto friend"><i class="fa fa-mail"></i></a>
            <?php endif; ?>
    </div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
    <script type="text/x-magento-init">
        {
        "#product_addtocart_form": {
        "Magento_Catalog/product/view/validation": {
        "radioCheckboxClosest": ".nested"
        }
        }
        }
    </script>
<?php else : ?>
    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Magento_Catalog/js/catalog-add-to-cart'
        ], function ($) {
            'use strict';

            $('#product_addtocart_form').mage('validation', {
                radioCheckboxClosest: '.nested',
                submitHandler: function (form) {
                    var widget = $(form).catalogAddToCart({
                        bindSubmit: false
                    });

                    widget.catalogAddToCart('submitForm', $(form));

                    return false;
                }
            });
        });
    </script>
<?php endif; ?>
